-- Analytics layer: star schema with three fact tables sharing conformed dimensions.
-- Surrogate keys use BY DEFAULT identity so the ETL can insert the special members
-- -1 (Unknown) and -2 (Not applicable) with explicit keys.
-- Indexes on fact foreign keys are deliberately not created here; they are added
-- and measured in the query optimisation phase (sql/indexes).

-- Dimensions -------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS analytics.dim_date (
    date_key           INTEGER PRIMARY KEY,          -- YYYYMMDD
    full_date          DATE NOT NULL UNIQUE,
    year               SMALLINT NOT NULL,
    quarter            SMALLINT NOT NULL,
    month_number       SMALLINT NOT NULL,
    month_name         TEXT NOT NULL,
    year_month         TEXT NOT NULL,                -- e.g. 2024-03, sorts correctly as text
    day_of_month       SMALLINT NOT NULL,
    day_of_week_number SMALLINT NOT NULL,            -- ISO: 1 = Monday ... 7 = Sunday
    day_name           TEXT NOT NULL,
    is_weekend         BOOLEAN NOT NULL,
    season             TEXT NOT NULL,                -- southern hemisphere
    is_analysis_period BOOLEAN NOT NULL              -- 2012-2024 complete years (DQ24)
);

CREATE TABLE IF NOT EXISTS analytics.dim_time (
    hour_key       SMALLINT PRIMARY KEY CHECK (hour_key BETWEEN 0 AND 23),
    hour_label     TEXT NOT NULL,                    -- e.g. 08:00-08:59
    time_band      TEXT NOT NULL,
    time_band_sort SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_location (
    location_key           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id                INTEGER UNIQUE,
    node_type_code         CHAR(1),
    node_type_desc         TEXT NOT NULL,
    latitude               NUMERIC(9, 6),
    longitude              NUMERIC(9, 6),
    lga_name               TEXT NOT NULL,
    dtp_region             TEXT NOT NULL,
    postcode               TEXT,
    road_name              TEXT,
    intersecting_road_name TEXT,
    location_label         TEXT NOT NULL,
    is_unincorporated      BOOLEAN NOT NULL,
    has_coordinates        BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_severity (
    severity_key        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity_code       SMALLINT UNIQUE,
    severity_desc       TEXT NOT NULL,
    is_fatal            BOOLEAN NOT NULL,
    is_fatal_or_serious BOOLEAN NOT NULL,            -- KSI: killed or seriously injured
    sort_order          SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_accident_type (
    accident_type_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accident_type_code SMALLINT UNIQUE,
    accident_type_desc TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_light_condition (
    light_condition_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    light_condition_code SMALLINT UNIQUE,
    light_condition_desc TEXT NOT NULL,
    is_dark              BOOLEAN
);

CREATE TABLE IF NOT EXISTS analytics.dim_road_geometry (
    road_geometry_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    road_geometry_code SMALLINT UNIQUE,
    road_geometry_desc TEXT NOT NULL,
    is_intersection    BOOLEAN
);

CREATE TABLE IF NOT EXISTS analytics.dim_speed_zone (
    speed_zone_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    speed_zone_code TEXT UNIQUE,
    speed_zone_desc TEXT NOT NULL,
    speed_limit_kmh SMALLINT,
    speed_band      TEXT NOT NULL,
    speed_band_sort SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_weather (
    weather_key      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weather_desc     TEXT NOT NULL UNIQUE,           -- e.g. 'Raining + Strong winds'
    condition_count  SMALLINT NOT NULL,
    has_clear        BOOLEAN NOT NULL,
    has_rain         BOOLEAN NOT NULL,
    has_snow         BOOLEAN NOT NULL,
    has_fog          BOOLEAN NOT NULL,
    has_smoke        BOOLEAN NOT NULL,
    has_dust         BOOLEAN NOT NULL,
    has_strong_winds BOOLEAN NOT NULL,
    is_not_known     BOOLEAN NOT NULL,
    weather_category TEXT NOT NULL                   -- one reporting group per combination
);

CREATE TABLE IF NOT EXISTS analytics.dim_road_surface (
    road_surface_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surface_desc     TEXT NOT NULL UNIQUE,           -- e.g. 'Muddy + Wet'
    condition_count  SMALLINT NOT NULL,
    has_dry          BOOLEAN NOT NULL,
    has_wet          BOOLEAN NOT NULL,
    has_muddy        BOOLEAN NOT NULL,
    has_icy          BOOLEAN NOT NULL,
    has_snowy        BOOLEAN NOT NULL,
    is_not_known     BOOLEAN NOT NULL,
    surface_category TEXT NOT NULL                   -- one reporting group per combination
);

CREATE TABLE IF NOT EXISTS analytics.dim_road_user_type (
    road_user_type_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    road_user_type_desc TEXT NOT NULL UNIQUE,        -- source codes 2/7 and 3/8 share a description
    sort_order          SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_injury_level (
    injury_level_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    injury_level_code SMALLINT UNIQUE,
    injury_level_desc TEXT NOT NULL,
    sort_order        SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_person_demographic (
    person_demographic_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age_group              TEXT NOT NULL,
    age_group_sort         SMALLINT NOT NULL,
    sex_code               CHAR(1),
    sex_desc               TEXT NOT NULL,
    UNIQUE (age_group, sex_code)
);

CREATE TABLE IF NOT EXISTS analytics.dim_vehicle_type (
    vehicle_type_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type_code TEXT UNIQUE,
    vehicle_type_desc TEXT NOT NULL,
    vehicle_category  TEXT NOT NULL
);

-- Facts ------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS analytics.fact_crash (
    accident_no               TEXT PRIMARY KEY,     -- degenerate dimension
    date_key                  INTEGER NOT NULL REFERENCES analytics.dim_date (date_key),
    hour_key                  SMALLINT NOT NULL REFERENCES analytics.dim_time (hour_key),
    location_key              INTEGER NOT NULL REFERENCES analytics.dim_location (location_key),
    severity_key              INTEGER NOT NULL REFERENCES analytics.dim_severity (severity_key),
    accident_type_key         INTEGER NOT NULL REFERENCES analytics.dim_accident_type (accident_type_key),
    light_condition_key       INTEGER NOT NULL REFERENCES analytics.dim_light_condition (light_condition_key),
    road_geometry_key         INTEGER NOT NULL REFERENCES analytics.dim_road_geometry (road_geometry_key),
    speed_zone_key            INTEGER NOT NULL REFERENCES analytics.dim_speed_zone (speed_zone_key),
    weather_key               INTEGER NOT NULL REFERENCES analytics.dim_weather (weather_key),
    road_surface_key          INTEGER NOT NULL REFERENCES analytics.dim_road_surface (road_surface_key),
    persons_killed            SMALLINT NOT NULL,
    persons_seriously_injured SMALLINT NOT NULL,
    persons_other_injury      SMALLINT NOT NULL,
    persons_not_injured       SMALLINT NOT NULL,
    persons_involved          SMALLINT NOT NULL,
    vehicles_involved         SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.fact_person (
    accident_no            TEXT NOT NULL,
    person_id              TEXT NOT NULL,
    date_key               INTEGER NOT NULL REFERENCES analytics.dim_date (date_key),
    location_key           INTEGER NOT NULL REFERENCES analytics.dim_location (location_key),
    severity_key           INTEGER NOT NULL REFERENCES analytics.dim_severity (severity_key),
    road_user_type_key     INTEGER NOT NULL REFERENCES analytics.dim_road_user_type (road_user_type_key),
    injury_level_key       INTEGER NOT NULL REFERENCES analytics.dim_injury_level (injury_level_key),
    person_demographic_key INTEGER NOT NULL REFERENCES analytics.dim_person_demographic (person_demographic_key),
    vehicle_type_key       INTEGER NOT NULL REFERENCES analytics.dim_vehicle_type (vehicle_type_key),
    taken_to_hospital      BOOLEAN,
    PRIMARY KEY (accident_no, person_id)
);

CREATE TABLE IF NOT EXISTS analytics.fact_vehicle (
    accident_no       TEXT NOT NULL,
    vehicle_id        TEXT NOT NULL,
    date_key          INTEGER NOT NULL REFERENCES analytics.dim_date (date_key),
    location_key      INTEGER NOT NULL REFERENCES analytics.dim_location (location_key),
    severity_key      INTEGER NOT NULL REFERENCES analytics.dim_severity (severity_key),
    vehicle_type_key  INTEGER NOT NULL REFERENCES analytics.dim_vehicle_type (vehicle_type_key),
    occupants         SMALLINT,
    vehicle_age_years SMALLINT,                      -- NULL when year of manufacture is unknown
    PRIMARY KEY (accident_no, vehicle_id)
);
