"""Run every query in sql/analytics and write the results to docs/analysis_results.md.

Each SQL file starts with a "-- Question:" comment; it becomes the section heading.
Usage:
    python -m src.analysis.run_analysis
"""

import logging
import time
from datetime import date
from decimal import Decimal
from pathlib import Path

from src.utils.db import get_connection

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ANALYTICS_SQL_DIR = PROJECT_ROOT / "sql" / "analytics"
RESULTS_PATH = PROJECT_ROOT / "docs" / "analysis_results.md"

logger = logging.getLogger(__name__)


def header_comment(sql_text: str) -> list[str]:
    """Return the leading comment block without the '-- ' prefix."""
    lines = []
    for line in sql_text.splitlines():
        if not line.startswith("--"):
            break
        lines.append(line[2:].strip())
    return lines


LABELS = ("Question:", "Approach:", "Techniques:", "Caveat:", "Note:", "Grain:")
NOTE_LABELS = ("Approach:", "Caveat:", "Note:", "Grain:")
# Integer columns that are identifiers or positions, not quantities, so no thousands separator.
PLAIN_INTEGER_COLUMNS = {"year", "hour", "rank", "top_pct_of_locations"}


def labelled_comments(comment_lines: list[str]) -> dict[str, str]:
    """Group the header comment into {'Question:': '...', 'Caveat:': '...'}, joining continuation lines."""
    sections: dict[str, list[str]] = {}
    current = None
    for line in comment_lines:
        label = next((label for label in LABELS if line.startswith(label)), None)
        if label:
            current = label
            sections[current] = [line.removeprefix(label).strip()]
        elif current and line:
            sections[current].append(line)
    return {label: " ".join(parts) for label, parts in sections.items()}


def format_value(value, column: str) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return str(value) if column in PLAIN_INTEGER_COLUMNS else f"{value:,}"
    if isinstance(value, float):
        return f"{value:,.1f}"
    if isinstance(value, Decimal):
        return f"{value:,}" if value == value.to_integral_value() and value.as_tuple().exponent >= 0 else str(value)
    if isinstance(value, date):
        return value.isoformat()
    return str(value).replace("|", "\\|")


def markdown_table(columns: list[str], rows: list[tuple]) -> list[str]:
    return [
        "| " + " | ".join(columns) + " |",
        "|" + "---|" * len(columns),
        *("| " + " | ".join(format_value(v, c) for v, c in zip(row, columns)) + " |" for row in rows),
    ]


def run_query_file(connection, sql_file: Path) -> list[str]:
    sql_text = sql_file.read_text(encoding="utf-8")
    started = time.perf_counter()
    cursor = connection.execute(sql_text)
    rows = cursor.fetchall()
    columns = [column.name for column in cursor.description]
    logger.info("%s: %d rows in %.2f s", sql_file.name, len(rows), time.perf_counter() - started)

    comments = labelled_comments(header_comment(sql_text))
    notes = [f"**{label}** {comments[label]}" for label in NOTE_LABELS if label in comments]
    return [
        f"## {sql_file.stem.replace('_', ' ')}",
        "",
        f"**{comments.get('Question:', '')}**",
        "",
        f"Query: [`sql/analytics/{sql_file.name}`](../sql/analytics/{sql_file.name})",
        "",
        *(["\n>\n".join(f"> {line}" for line in notes), ""] if notes else []),
        *markdown_table(columns, rows),
        "",
    ]


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    lines = [
        "# Analysis Results",
        "",
        "Generated by `python -m src.analysis.run_analysis` from the loaded database. Do not edit by hand.",
        "Interpretation of these results is in [`key_insights.md`](key_insights.md).",
        "",
        "All figures are **injury crashes** (the dataset has almost no non-injury crashes). "
        "KSI = killed or seriously injured.",
        "",
    ]
    with get_connection() as connection:
        for sql_file in sorted(ANALYTICS_SQL_DIR.glob("*.sql")):
            lines += run_query_file(connection, sql_file)
    RESULTS_PATH.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Results written to %s", RESULTS_PATH)


if __name__ == "__main__":
    main()
